export enum INCOMPLETE_ISSUE_TYPE {
	EMPTY_CONTENT = "EMPTY_CONTENT",
	EMPTY_CONTENT_HEADING = "EMPTY_CONTENT_HEADING",
	INCOMPLETE_SYNTAX = "INCOMPLETE_SYNTAX",
	INCOMPLETE_BOOK = "INCOMPLETE_BOOK",
	INCOMPLETE_BLOG_ARTICLE = "INCOMPLETE_BLOG_ARTICLE",
	INCOMPLETE_PAPER = "INCOMPLETE_PAPER",
	INCOMPLETE_VIDEO = "INCOMPLETE_VIDEO",
}
